Foreground yes
User clamav
TCPSocket 3310
TCPAddr 127.0.0.1
DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.ctl
FixStaleSocket yes
LogTime yes
LogClean no
MaxScanSize 20M
MaxFileSize 16M
StreamMaxLength 16M
MaxScanTime 15000
MaxThreads 4
ReadTimeout 20
CommandReadTimeout 5
ExitOnOOM yes
